title: Portfolio
author: Lim Ting-iong 林庭揚
copyright: "2026. Licensed under CC BY-NC-ND 4.0 "
logo: figure/hamster.png


execute:
  execute_notebooks: auto

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/iong2k/portfolio
  branch: main

html:
  favicon: figure/favicon.png
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: false

hide_input: true